<Project>
  <PropertyGroup>
    <GridInfluenceVersion>0.1.0-alpha.1</GridInfluenceVersion>
    <LangVersion>14</LangVersion>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <DebugType>portable</DebugType>
    <EmbedAllSources Condition="'$(ContinuousIntegrationBuild)' == 'true'">true</EmbedAllSources>
    <PathMap Condition="'$(ContinuousIntegrationBuild)' == 'true'">$(MSBuildThisFileDirectory)=/_/</PathMap>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
</Project>
